### ISSUE TITLE
Master volume for contexts

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#12]
Is there any chance some kind of master volume could be introduced?

I know there's gain on a per-source basis, but it would be great if there was a way to have more fine grained control over volume.

Either that, or could sources be slaved to other sources? So you could have a sounds volume source, to which you could connect all related sources, to have like a master volume?

Sorry if this is already implemented somehow, and I just don't know what I'm doing.

**Comment by camlorn** [comment]
It's not implemented.  Master volume on contexts isn't a bad idea but you're not encouraged to create more than one per app, so I wouldn't get in the habit of using them as a separation mechanism.  Eventually every context will be opening an audio device, though at the moment they try to share.

As an interim solution you can create an abstraction of your own that collects sources into groups and then `group.set_gain(bla)` yourself.  Synthizer will eventually offer this as something like a `SourceController` or somesuch that you register sources with.  This is something that's on the roadmap, all be it the roadmap that only exists in my head.

What master volume is actually useful for (when I code it) is adding headroom to prevent clipping.

**Comment by chrisnorman7** [comment]
OK, grouping sources is a great idea. Thanks.
