### ISSUE TITLE
Support vendoring Synthizer in other projects

### ISSUE THREAD

**Issue by camlorn** [synthizer/synthizer#18]
Synthizer is currently a single-repository project with no external dependencies.  99% of CMake is just listing files.  Python and Rust could both benefit from being able to just embed the files without requiring the user to have CMake.  We can:

- Write and maintain a .yaml file at the root of the repository which contains:
  - A list of files and glob patterns for the things in the repository that are needed to build.
  - A list of repository-relative include paths.
  - A list of defines to pas to the C compiler, unfortunately required because of WDL (though we could fork WDL, or do any of several other things, if necessary).
- Write a script which takes this yaml file, transcodes it to JSON, and creates a directory with the globbed files that are needed to build, minus supplementary documentation/examples/etc.
- make the Python bindings support this flow, then integrate building Python's bindings this way in CI to make sure that the vendoring procedure can't ever fall out of date.

This presumes that most users are not going to want to try to link multiple things to the same Synthizer library or, put another way, that the primary use case is `pip install synthizer` and then use it from a pure Python (or Rust or whatever) codebase.  But for those cases, most languages have feature flags, so it would be possible to disable the vendoring that way on a case-by-case basis.  This also potentially opens us up to being able to produce an Sqlite-style amalgamation.

Going to CC @ndarilek here.  Would this solve problems in Rust land?  I think it solves problems in Python land.

Blocked on #1, kind of.  We could do this first, but there's not much point until we're no longer Windows and Clang only.

**Comment by ndarilek** [comment]
Rust has pretty decent support for calling external tools from build.rs, 
up to and including recommending it in Cargo's various packaging docs, 
so I don't think I'd need anything special in this regard. I haven't 
looked at the buildscript in a while, but I'm pretty sure it isn't doing 
anything odd other than calling cmake directly so I can force some 
things that aren't auto-detected, and I can probably fall back to the 
cmake crate once #1 is resolved.


Happy to revisit and confirm after the compiler support is more generic, 
but I can't imagine needing a list of source files or having to manually 
run the compiler. Unless Python needs it, I'd rather the Synthizer build 
system just do the right thing and work with any reasonable toolchain.


Thanks.

**Comment by camlorn** [comment]
I've been presuming that the insert-any-language people don't necessarily have CMake, but perhaps it's reasonable to assume Rust people will install it.  The CMake build system will do the right thing irregardless of any outcome here.

Ideally I want to publish a miniaudio style amalgamation, but at the moment that doesn't seem possible. This is the next best thing I could come up with; in Python, calling out to CMake reliably doesn't seem to at all be a thing.  I'll leave this for now.  Maybe others watching the repository will chime in.  We've got Python wheels, so this can pretty much be put off until whenever, and I'd rather have a resounding "this is a great idea" if I'm going to go through the trouble of maintaining it.

**Comment by camlorn** [comment]
Discussion in #1, #19, and #15  has made it clear that this approach probably can't scale, so closing this out.  Perhaps one day I can just produce an amalgamation, but that day is not today.
