### ISSUE TITLE
occlusion filters

### ISSUE THREAD

**Issue by ahicks92** [synthizer/synthizer#25]
We'll want a per-source filter for occlusion purposes.  Probably this will just be integrating a set of standard "this has a filter" properties into sources or, possibly, a `syz_configureFilter` function (since filters need to be updated atomically).  There's no particular reason to make the API specifically for occlusion, but occlusion is the primary motivating factor.

**Comment by ultrasound1372** [comment]
Will these have a sort of dry/wet control? Or would we use sweeps? To model temporary obstruction, closing door doesn't block it all at once, etc. And if convolution is in the mix, there should be fading on that as well.

**Comment by camlorn** [comment]
Yes. There will be all the appropriate things.  This isn't my first time doing this stuff.
