### ISSUE TITLE
Can't build Synthizer v0.7.7 with MSVC

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#33]
I think that CMakeLists.txt got rolled back somehow when you released 0.7.7, it no longer checks if the compiler is Clang before adding a bunch of Xclang options that MSVC doesn't know what to do with.

**Comment by camlorn** [comment]
Yes, it did.  0.7.7 had to drop a bunch of things.  This should be fixed in 0.7.8, whenever that happens.
