### ISSUE TITLE
Still getting stuttering sound after a looping BufferGenerator has been destroyed

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#36]
Hi,
Not sure if you already know about this one, but sometimes I'm still getting sound playing after I've destroyed a BufferGenerator.

Unfortunately, I couldn't write standalone code that would reproduce the error, but it happens when running the earwax test suite if that helps any.

If you've got no idea what I'm talking about, please let me know, and I'll work harder to get some code that reproduces the problem.

As it stands, it happens 3 times out of 5.

**Comment by camlorn** [comment]
What does stuttering mean?  Is it producing a constant buzz, or is it acting like the generator is still managing to advance but distorted?

**Comment by chrisnorman7** [comment]
Less like a buzz, and more like it's looping just a few samples worth. It's
clearly part of the sound that was originally playing; but not the whole of
it.

I can upload an example, if that would help?

**Comment by camlorn** [comment]
Probably not.  I'm going to have to see if I can duplicate it.  Chances that this is actually another test and your test suite runs in parallel?  I believe that might be the py.test default.

**Comment by chrisnorman7** [comment]
Not sure, although I think not.

I certainly haven't done anything special to make it run in parallel, and
I've not installed the pytest-xdist plugin, so as far as I know, it's
running sequentially.

Take care,

Chris Norman

**Comment by camlorn** [comment]
I also can't reproduce this outside the test suite.  That means either I fixed it already, or your test suite is doing something.  Given that you've got two issues related to the test suite, my guess is that eventually they're going to become the same issue once we know what something is.

Can you confirm whether this is happening post 0.8.1?

**Comment by chrisnorman7** [comment]
Nope, all seems to be fine now. Thank you.
