### ISSUE TITLE
Some properties that affect audio are noticeably slow to update

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#38]
When adjusting certain properties such as Source.gain, Source3D.position, BufferGenerator.position or when shutting down the library, it takes about 200 MS for the change to be reflected.

**Comment by thgcode** [comment]
Are you experiencing these delays without adjusting properties, just playing the sound? I'm not sufe if it's related to the properties or something delaying the sending the samples to the sound card

**Comment by Keithcat1** [comment]
When I change the properties, there is a noticeable delay before the playing sound reflects the change.

**Comment by camlorn** [comment]
When I did the linux work, I accidentally switched Miniaudio from low latency to conservative, and apparently never reverted that change.

I'll have a release to try up shortly. If that doesn't do it, I can follow up with some other config tweaks that will, but would rather start with Miniaudio managing the values for us before trying to manually tune.

It would be helpful to know what platform, in case this persists.

**Comment by camlorn** [comment]
Sorry, didn't mean to close this.

Also, CC @chrisnorman7 because this is probably the other half of his latency problems as well.

**Comment by thgcode** [comment]
Apparently the revert solved the delay for me. I'm testing on Windows.

**Comment by camlorn** [comment]
Ok, 0.8.1 is up and should improve this a lot.

**Comment by camlorn** [comment]
Going to close this out because we've got a confirm from someone else and it's definitely working on my machine.  Feel free to reopen if you still have issues with it.
