### ISSUE TITLE
Synthizer is consooming a lot of memory

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#44]
This seems to happen when I run any program that uses Synthizer, such as the Python media player example.
The longer the program runs, the higher and higher the memory usage becomes. It's not loading buffers.
Also, after running said Python media player example for about a minute and exiting it, I noticed this:
debug(unknown-thread 3) Deferred free processed 340 frees in a background thread                                                                                      
Using Synthizer 0.8.4

**Comment by camlorn** [comment]
The deferred free counter isn't really related.  I wouldn't draw conclusions off that.

I'll try to duplicate this. Suspect I know what it might be.

**Comment by camlorn** [comment]
Yeah, confirmed on my machine. I'll try to get a fix this weekend.

**Comment by camlorn** [comment]
Ok, just pushed 0.8.5 and this should now be fixed.

For your reference, in the case of this example, the deferred free count thing is a function of the length of the media file passed in.
