### ISSUE TITLE
Lua Binding

### ISSUE THREAD

**Issue by ctoth** [synthizer/synthizer#48]
This library is a fantastic effort that will seriously improve access to 3D audio.
I'd like to provide a Lua binding. This is useful for many game engines, as well as enabling MUSHClient to use Synthizer.
Is this something that would be accepted upstream?

**Comment by camlorn** [comment]
If something makes it into this repo and/or under this org, I'm making a commitment to maintain it.  For that reason, I'm only taking bindings upstream that I have the interest and bandwidth to maintain myself.

The real problem with Lua is that  there's something like 3 or 4 ways to do it, so even if I did have the bandwidth/interest it's not possible to satisfy everyone.  I think the only "global" way is a Lua C extension, but pretty sure that falls over as soon as someone's using LuaJIT.  I can't justify maintaining something for the small percentage of Lua users who happen to be able to consume the bindings however they get written plus happen to be using something where you can just bring in a third party C thing (e.g. if Synthizer is in an engine, you probably have to work out how to share it between the script and the rest of the engine, which is entirely different than stand-alone library for Mushclient).

Feel free to write/maintain one, though.  The API surface area is pretty small, though things will shift around a bit more until 1.0.
