### ISSUE TITLE
Intermittent Windows error when disconnecting reverbs in tests

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#50]
I'm trying desperately to track this down to some minimal code for you, but wanted to let you know there's a problem:

50% of the time when I run my tests they pass, and the rest of the time I get `Windows fatal exception: access violation`.

It seems to happen when reverbs are disconnected too quickly. I can only infer that because the failure rate seems to go up when decreasing a call to sleep between the reverb being connected and disconnected.

I've googled, but I'm struggling to find out much information about these enigmatic exceptions, other than they seem to come up most often when pytest is used. I'm sure I read somewhere that they normally happen, but something to do with pytest's fault handler exposes them.

Not sure if that means this is actually a bug in pytest or not.

I've tried running `py.test --collect-only`, to see if it's an error in one of my fixtures, or the teardown of Synthizer itself, but no dice.

I've managed to create a minimal test framework, but it uses Earwax's Sound object. I'm trying to copy in all the relevant stuff, so you can debug with the smallest amount of dependencies possible.

If you could let me know if any of this is ringing bells, then I can stop and get on with other things haha.

**Comment by chrisnorman7** [comment]
OK, sod's law, that was quicker than I feared:

### Setting up

To make this work, set yourself up a new tests directory, and create the following files:

### tests/conftest.py

```python
"""Set up tests."""

from typing import Generator

import synthizer
from pytest import fixture


@fixture(autouse=True)
def setup_tests() -> Generator[None, None, None]:
    """Test framework."""
    with synthizer.initialized():
        yield


@fixture(name="context")
def get_context() -> synthizer.Context:
    """Get an audio context."""
    return synthizer.Context()


@fixture(name="reverb")
def get_reverb(context: synthizer.Context) -> synthizer.GlobalFdnReverb:
    """Get a reverb."""
    return synthizer.GlobalFdnReverb(context)


@fixture(name="source")
def get_source(context: synthizer.Context) -> synthizer.DirectSource:
    """Get a source."""
    return synthizer.DirectSource(context)


@fixture(name="generator")
def get_generator(context: synthizer.Context) -> synthizer.BufferGenerator:
    """Return a generator."""
    g: synthizer.BufferGenerator = synthizer.BufferGenerator(context)
    b: synthizer.Buffer = synthizer.Buffer.from_stream("file", "sound.wav")
    g.buffer = b
    return g
```

### tests/reverb_test.py

```python
"""Test Synthizer."""

from time import sleep

from synthizer import BufferGenerator, Context, DirectSource, GlobalFdnReverb


def test_disconnect_reverb(
    context: Context,
    reverb: GlobalFdnReverb,
    source: DirectSource,
    generator: BufferGenerator,
) -> None:
    """Make sure we can easily detach a reverb."""
    source.add_generator(generator)
    context.config_route(source, reverb)
    sleep(1)
    context.remove_route(source, reverb)
```

### Results

When I run this, it works about 2 times out of 5.

**Comment by camlorn** [comment]
I'm going to look into this as time allows, but for your reference access violation means that there's a bug in the C++ side, kind of akin to reading past the end of the list or trying to do something with a value that's None (C++ groups them together, it's not always reliably reported, but eh).  You'll not always necessarily get that error due to Synthizer (though in this case it almost certainly is).  But you'll definitely never get it from a Python-only library, or because of Python itself.  It requires a buggy C extension to be involved first.

**Comment by chrisnorman7** [comment]
Well, put it this way. No matter how I use Synthizer reverb currently, my
code crashes. While I'm sure some of that is Earwax, with no tracebacks, I
can't track anything down.

Any time I try to play more than a couple of sounds through the same
reverb, it just crashes. No error, no nothing.

Can you give me some pointers on where to look? I've tried everything I can
think of, barring creating a mini game without Earwax to test just
Synthizer.

Take care,

Chris Norman

**Comment by camlorn** [comment]
No, I can't.  It's going to probably be something stupid on my side.  I'll write a program to hammer on it and run under asan as soon as I have the bandwidth to do so.

**Comment by camlorn** [comment]
It was something on my side.  Pushing 0.8.7 in a few minutes. If you could confirm that this is fixed I'd appreciate it.  Hopefully it's not also going to be something else on my side.

**Comment by chrisnorman7** [comment]
Magic, thank you.

It *seems* to work. I'll check properly when I'm not on night shift.

Take care,

Chris Norman

**Comment by camlorn** [comment]
Going to go ahead and close this out, but feel free to reopen if it still happens.

**Comment by chrisnorman7** [comment]
I’m sorry, thought it was already closed actually.

It's all working fine, far as I can tell.
