### ISSUE TITLE
Something is up with PannedSource.PanningScalar

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#51]
When I run this code:
from synthizer import *
import sys, time
with initialized():
	ctx=Context()
	buf=Buffer.from_stream("file", sys.argv[1])
	gen=BufferGenerator(ctx)
	gen.buffer=buf
	src=PannedSource(ctx)
	src.add_generator(gen)
	src.panning_scalar=1
	time.sleep(buf.get_length_in_seconds())
I expect that the sound will play on the far right, but it plays in the center instead.

**Comment by camlorn** [comment]
Closed in favor of #52 which comes with an explanation that's probably the bug.
