### ISSUE TITLE
If you set PannedSource.panning_scalar too quickly, it has no effect

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#52]
Hi,
With the code:

```python
from time import sleep

from synthizer import Context, initialized, PannedSource, StreamingGenerator

with initialized():
    c = Context()
    p = PannedSource(c)
    g = StreamingGenerator(c, 'file', 'sound.wav')
    g.looping = True
    p.add_generator(g)
    p.panning_scalar = -1
    sleep(1)
```

The sound stays in the centre.

If you add another clal to `sleep`, right before setting the `panning_scalar`, it behaves normally:

```python
from time import sleep

from synthizer import Context, initialized, PannedSource, StreamingGenerator

with initialized():
    c = Context()
    p = PannedSource(c)
    g = StreamingGenerator(c, 'file', 'sound.wav')
    g.looping = True
    p.add_generator(g)
    sleep(1)
    p.panning_scalar = -1
    sleep(1)
```

The sound moves over to the left after the allotted second.

**Comment by chrisnorman7** [comment]
As an aside, the `panning_scalar` attribute of the source looks OK, but the sound is most definitely not panned right.

**Comment by Keithcat1** [comment]
There is already an issue for this, #51

**Comment by chrisnorman7** [comment]
Sorry, you're absolutely right.

Thanks for pointing that out. I should have searched first.

**Comment by camlorn** [comment]
I'm actually going to switch these around in favor of this one, because I'm almost sure the diagnosed behavior from @chrisnorman7 found is the bug.  Not sure how I'm going to fix it though.
