### ISSUE TITLE
non looping Sources with pitch bended generators of any pitch other than 1.0 and shorter than around 40000 samples produce unwanted results

### ISSUE THREAD

**Issue by masonasons** [synthizer/synthizer#55]
This started happening recently. Playing of sounds at any pitch lower or higher than normal of any source type with data shorter than around 40000 samples produces buzzing artifacts and doesn't actually play the sound.

**Comment by camlorn** [comment]
Can you attach an example file, please?  I might be able to do without but it'll speed things up.

That's a weirdly specific (and large) sample count.  I assume looping with pitch bend works on larger files?

**Comment by masonasons** [comment]
Yes, pitch bending larger files seems to work correctly.

Here is a file I'm having issues with pitching up or down.

**Comment by masonasons** [comment]
-

**Comment by camlorn** [comment]
This should now be fixed. 0.8.9 will be out later today.

Not sure why the length of the file mattered, though I suspect it's just that you didn't try bigger ones: the underlying bug would always happen on everything.  So possibly this isn't actually fixed, in which case feel free to reopen.

**Comment by masonasons** [comment]
Just tested, and It's fixed!
