### ISSUE TITLE
Ungraceful exit with invalid file formats

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#6]
If you try to load a text file for example, or a directory into synthizer, it raises SynthizerError, which is great.

If you try to load an MP3 file however, you get the following:

```bash
(env) C:\Users\chris\synthizer>python test.py "..\Dropbox\Fade Into You Final Mix.mp3"
debug(background-thread 1) Background thread started
debug(context-thread 2) Thread started
debug(unknown-thread 3) Format dr_wav returned nullptr. Skipping
debug(unknown-thread 3) Format dr_flac returned nullptr. Skipping
debug(unknown-thread 3) Format stb_vorbis returned nullptr. Skipping
```

IMHO, it should handle MP3 files the same way it handles text files.

**Comment by camlorn** [comment]
It's detecting that it's mp3, then crashing.  I will probably need to improve the logging here.  Do you have ffprobe?  If not you can get it via apt in WSL. Can you run ffprobe -i myfile.mp3 and paste the output?  I have a few ideas what this is and will try to fix this if I have the time this weekend, but if I can't figure it out that metadata will be useful.

**Comment by camlorn** [comment]
Solved, your file needs resampling.  I'll put this out in the next release.  For now, the magic command is:

```
ffmpeg -i file.mp3 -ar 44100 file.mp3
```

Note that that modifies in place; you may or may not want to name the output file something else.
