### ISSUE TITLE
Possible oversight in Python bindings

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#62]
In `synthizer.pyx`, in the definition for `Context.config_route`, there are the lines:

```python
        syz_initRouteConfig(&config)
        if filter:
            config.filter = filter.config
        else:
            _checked(syz_initRouteConfig(&config));
```

Should the `_checked` call be made only if setting the filter? I'm wondering if it should instead be:

```python
        syz_initRouteConfig(&config)
        if filter:
            config.filter = filter.config
        _checked(syz_initRouteConfig(&config));
```

Thanks.

**Comment by ahicks92** [comment]
Well, honestly the second init shouldn't even be there so I will kill that on the 0.9 branch (this isn't doing harm, unless you found an actual bug, and I don't feel like backporting noncritical things).

**Comment by chrisnorman7** [comment]
Fair enough. I just wanted to check in case there was some clever
undocumented thing you'd done.

Just so I know not to include it in my Dart bindings.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
I don't do undocumented things.  Buggy ones, yes, being as I'm trying to move very rapidly at the moment.  But the bindings don't use anything library-private.  You should error check the return value, though, if you're wondering which one is correct.

**Comment by chrisnorman7** [comment]
Yes, I've basically implemented your _checked method in Dart.

Take care,

Chris Norman
