### ISSUE TITLE
Build a DLL under Windows

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#63]
Hi,
I know this isn't so much a bug, because it works, but I can't figure out how to build a DLL on windows.

I know @ahicks92 has told me how to do it, and I always forget. Is it worth putting this command into the build section of the README? Or is this just a C thing that anyone who knows anything about Ninja should "just know"?

Cheers.

**Comment by chrisnorman7** [comment]
For anyone else trying to build a DLL quickly, the commands seem to be as follows:

```bash
cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL -DSYNTHIZER_LIB_TYPE=SHARED
ninja
```

**Comment by ahicks92** [comment]
Yeah, that's right.  But it is probably worth writing this down in the readme, so I'll make a point of doing that in the near future and then close this out.

**Comment by chrisnorman7** [comment]
Awesome, thank you.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
Looks like this was done a while ago and I forgot to close it out.
