### ISSUE TITLE
It is unclear which reverb gain to use

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#65]
Hi,
This comes with my usual proviso that it could just be me being stupid, but I am unclear whether to set the gain of a given reverb, or whether to set the gain in the call to `syz_configRoute` or whatever it's called.

Am I missing something? Or are they interchangeable?

Thanks in advance.

**Comment by ahicks92** [comment]
syz_routingConfigRoute configures the gain of the route, e.g. you can have multiple sources pointing at the same reverb with different gains, to do things like feed half the source to each reverb.  that's documented [here](https://synthizer.github.io/concepts/effects.html):

Gains are per route and apply after the gain of the source. For example, you might feed 70% of a source's output to something (gain = 0.7).
Filters are also per route and apply after any filters on sources. For example, this can be used to change the filter on a per-reverb basis for a reverb zone algorithm that feeds sources to more than one reverb at a time.

**Comment by chrisnorman7** [comment]
OK thank you. Makes sense.

Take care,

Chris Norman
