### ISSUE TITLE
Add something that simulates BASS's ability to set logarithmic curve on pan and volume

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#67]
Docs:
[http://www.un4seen.com/doc/#bass/BASS_CONFIG_CURVE_VOL.html](http://www.un4seen.com/doc/#bass/BASS_CONFIG_CURVE_VOL.html)
It does mention DB in the description, but then I remember you saying DB could only be used for volume / gain or something like that and BASS is clearly using it for pan too.

**Comment by ahicks92** [comment]
So my gut reaction is no, but I'll leave this open for counterarguments for a while.  This is standard Db, e.g. `10^(db/20)` to get to the scalar value.  My arguments against, not in priority order:

- If it's a setting that can only be set for some properties, it's reasonable to ask for it for other properties.
- Db isn't necessarily the only curve you'd want.
- If it's a per-property setting there's a lot of work both in the library itself and for binding developers, whereas you can just `10^(db/20`.
- If the setting is actually not per object, then you can't copy/paste someone else's code into your project if they assumed the opposite, or use someone else's library, or whatever.  It splits the ecosystem between libraries that turn it on and libraries that turn it off.
- Db has a lot of weird nonintuitive properties that I go into in the manual some, for example `-3 db + -3 db` isn't `-6 db`.  All the reasoning about for example if something is going to clip when you play it next to something else has to be done in boring old scalar gains.

For what it's worth my plan is to eventually move `SYZ_P_CLOSENESS_BOOST` off db as well.  And obviously some of the above arguments can only be resolved with more than just a few lines somewhere.  I think a good way of putting it is that bass values being newbie friendly, but Synthizer values being...correct isn't exactly the right word, maybe opinionated.

**Comment by ahicks92** [comment]
Closing this for lack of counterarguments.
