### ISSUE TITLE
Trying to play more than one lingering sound at a time causes silence

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#68]
Below is a Python example that I'm using to reproduce this. It plays all the files you specify on the command line. If you pass only one, it works, but if you pass two or more it makes a small popping noise followed by silence.
I'm not sure if the problem is that I'm using dec_ref after setting the sound to linger. The manual doesn't mention anything about that and it works with one sound. If I remove the line that calls dec_ref, everything works, but I'm afraid it's leaking handles.
import sys
from synthizer import *
from time import sleep
with initialized():
	ctx = Context()
	src = DirectSource(ctx)

	for i in sys.argv[1:]:
		gen = StreamingGenerator.from_file(ctx, i)
		src.add_generator(gen)
		gen.config_delete_behavior(True, 0)
		gen.dec_ref()
	while True:
		sleep(0.5)

**Comment by ahicks92** [comment]
I've confirmed this.  And yes you do always need to delete your handles.

**Comment by ahicks92** [comment]
Can you try the artifacts from [this CI run](https://github.com/synthizer/synthizer/actions/runs/1118473271) and see if it's fixed?  I believe it is.  If so I'll push a release this weekend.

**Comment by Keithcat1** [comment]
Yeah, fixed. Thanks. Also modified my Python example to give each sound its own lingering source and that seems to work too.

**Comment by ahicks92** [comment]
All right, release is going out now. Closing this as part of that.
