### ISSUE TITLE
Unable to create buffers

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#7]
Hi,
Tested with this minimal code:

```python
import synthizer


with synthizer.initialized():
  c = synthizer.Context()
  b = synthizer.Buffer.from_stream(c, 'file', r'sounds\menus\activate.wav')
  print(b)
```

I get the following error:

```bash
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    b = synthizer.Buffer.from_stream(c, 'file', r'sounds\menus\activate.wav')
  File "synthizer\synthizer.pyx", line 322, in synthizer.Buffer.from_stream
  File "synthizer\synthizer.pyx", line 30, in synthizer._to_bytes
TypeError: encoding without a string argument
```

It doesn't seem t matter if the file exists or not.

I'm running Python 3.8.5, 64 bit.

Thanks for reading.

**Comment by SemihBudak** [comment]
We don't need contexts for buffers anymore; they have been decoupled.

**Comment by chrisnorman7** [comment]
Ah, lovely, thank you so much. I obviously haven't been keeping up with the thread.

**Comment by camlorn** [comment]
It's hitting a string marshalling thing with a context and dying.  I will see what I can do about fixing the error so that it's not so confusing, because I doubt this'll be the last time.

**Comment by camlorn** [comment]
Bleh, didn't mean to reopen. Sorry for the e-mail spam.
