### ISSUE TITLE
Loading or streaming a sound using libsndfile causes the first half-second of the sound to play twice

### ISSUE THREAD

**Issue by Keithcat1** [synthizer/synthizer#70]

**Comment by ahicks92** [comment]
Do you have more specifics?  I'll try to duplicate it, but I'm surprised I wouldn't have already found this and time is thin, so any info you have is appreciated.

I'll follow up on this when I can.

**Comment by Keithcat1** [comment]
Here's a Python example. Running it with one .ogg file causes this to happen.
I don't think it matters weather the sound is streaming or loading, or
what kind of source you use.
I just loaded the file and was able to make sound normal by seeking to
500 seconds. Did you test it with files that were a minute or two in
length?
import sys
from time import sleep
from synthizer import *
with initialized(libsndfile_path="sndfile.dll"):
	ctx = Context()
	src=DirectSource(ctx)
	for i in sys.argv[1:]:
		gen = StreamingGenerator.from_file(ctx, i)
		src.add_generator(gen)
	input()

**Comment by ahicks92** [comment]
I hate to say it but I can't duplicate this.  I may need a test file again or something.  I can't get a Python or C version in any configuration to do it.

**Comment by Keithcat1** [comment]
[ball.zip](https://github.com/synthizer/synthizer/files/7025957/ball.zip)

**Comment by ahicks92** [comment]
Nope, still no luck.  Sorry.

- What platform?  Looks like Windows from your example?
- Did you use the official Libsndfile from the installer or build it yourself?
- 32 bit or 64 bit?

If I can't get it to happen here there's very little I can do about it.

**Comment by Keithcat1** [comment]
Windows 10 (64-bit).
I got Libsndfile from here:
https://github.com/libsndfile/libsndfile/releases/tag/1.0.31

**Comment by ahicks92** [comment]
Yeah. You're using 1.0.31, but I've tested against 1.0.28.  it definitely happens there.  Clearly, they changed something or broke something or who knows.  Looking into this further, but if you use the one from [here](http://www.mega-nerd.com/libsndfile/) it should work.

**Comment by ahicks92** [comment]
If you download their release and extract it, sndfile-play.exe also chokes on that file but in a different fashion.  I think this is a libsndfile-side bug with ogg, but I don't have the bandwidth to seriously follow up on it.  I suggest seeing if sndfile-play is breaking on oggs for you and, if so, open an issue against them and see what comes of it.  can you confirm that sndfile-play from their release also breaks on your machine before I take this much further?

**Comment by ahicks92** [comment]
Closed because the next version will be ripping out libsndfile.
