### ISSUE TITLE
Figure out what to do about long-term maintenance of the Python bindings

### ISSUE THREAD

**Issue by ahicks92** [synthizer/synthizer#74]
I'm moving to Rust for my new projects for a variety of reasons, but as regards Synthizer it's actually something like 5x easier to write Rust bindings due to proper macro support and things like that.  With #73, it's becoming evident that maintaining them long-term is going to become a burden, and I need to shift things off me if I'm going to have time to work on things like [ammo](https://github.com/audio-mmo/monorepo).  until now, the primary thing you had to do to the Python bindings is just declare new properties with the occasional function, but that's changing; the upshot is that not only is doing the Rust bindings as my primary non-C maintenance in alignment with my future projects, it's actually easier and faster to use them as a testbed.  So, we have some paths:

- It turns out I'm wrong, Rust was a terrible choice for testing stuff via, and I go back to Python.
- We find someone comfortable maintaining Python who's willing to take on the commitment.
- We find a way to maintain Python more easily, which basically means doing some really incredibly ugly stuff like generating a Cython .pyx file via running Jinja templates to have something like Rust macros.
- It turns out no one really cares about Python and we just drop it (which is unlikely, but eh, I'm dumping context in an issue).

The work for #73 is going to be the determining factor with respect to whether or not the path forward is Rust.  After that we'll see. I estimate the timeline on resolving this discussion to be ~6 weeks.  If you want to nominate yourself as a maintainer, you need enough background knowledge to be comfortable with C and Cython: if you don't know either, this isn't a good learning project.

**Comment by ahicks92** [comment]
I think that currently the approach here is that I'm going to extract the bindings as part of the next release, then maintain them until the next major feature on the order of #73 (e.g. we get #73 in them, but after that next time I don't put in the time).

Not sure what happens to the tutorials.  Probably I port them to C, which to be honest they probably should have been in C in the first place.

**Comment by chrisnorman7** [comment]
Once you've included #73 then I think that's all *most* people will need anyways. You could just say "That's it, move to Rust or be happy with the old Synthizer stuff".

It's also not like there's no other bindings: You're doing the Rust ones, I've got Dart that I suspect I'll be maintaining long term, and that's just the ones I know about.

**Comment by ahicks92** [comment]
I could, yes.  But there's a lot more stuff that Synthizer is likely to grow as I need it for ammo and I'd rather not just give up on Python given the importance in the audiogaming community (also, almost no one who's doing only Python can leave for Rust, though Dart is an option).  Broadly speaking I don't object to e.g. reviewing prs on it, but I'm looking at the 4-6 hours for automation and going "well there goes 4-6 hours I could spend adding features" and that's a whole week of outside work time gone.  It's more of a I don't have a choice thing.  Fortunately adding a new generator or something is 10 minutes typically.

On the other hand this issue has gotten zero participation and there's a grand total of maybe 2 or 3 released things in Python using Synthizer.  SO we'll see what happens after the next release when I make this issue really really obvious.  "I won't be maintaining Python long term" getting this little of a response seems to indicate that there's only hypothetical interest from the audiogaming crowd, and no one outside that circle cares about Python because graphics.  Perhaps everyone doing things beyond the newbie level no longer uses Python or never did, or maybe it's just the typical problem in that circle of almost no one being able to do projects far enough to be able to make use of HRTF.  At the risk of being a self-fulfilling prophecy or something, if there's no indication that someone cares, then "well nevermind Python" is pretty much the response that will come out of this issue until and/or unless I start caring about Python again, which is possible.  I wouldn't use Rust for everything.  But when you look at GCP and go "224 core vms mean I never have to worry about splitting it between boxes if it's successful, that's way more than it could ever use, isn't that a relief" Python just won't cut it and I'm not retired yet.

**Comment by chrisnorman7** [comment]
Makes sense.

I mean I'm sure some of it is that people love using Synthizer but don't
have the technical know-how to take on the bindings. If that's the case
then that's fine: They'll be fine not having many of the future features
too.

Also, if it bothers someone that much, they can take over the bindings.
Even if they have to learn Cython, it's all good knowledge to have.

Take care,

Chris Norman

**Comment by ahicks92** [comment]
The final answer to this issue is that the Synthizer Python bindings now live [here](https://github.com/synthizer/synthizer-python) with directions on the development workflow to update them and I'll update them as I feel like it but keep the responsibility of reviewing PRs and doing releases.  E.g. Python style BDFL.

Closing this out.  I'll still give them automation, as previously stated.  But that's probably mostly it after that.

**Comment by chrisnorman7** [comment]
Yeah, that works.

Take care,

Chris Norman
