### ISSUE TITLE
Trying to create a Buffer instance from an invalid file fails silently

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#8]
Hi,
When running the below code, trying to open the file results in a silent crash, with no tracebacks:

```python
import sys

import synthizer

with synthizer.initialized():
  print('Hello.')
  b = synthizer.Buffer.from_stream('file', sys.argv[0])
  print('Goodbye.')
  print(type(b))
```

I know that file is invalid, but I'm reasonably sure Synthizer used to raise SynthizerError when trying to open an invalid file.

**Comment by camlorn** [comment]
This will be in the next release. And yes, it did used to work.
