### ISSUE TITLE
[Proposal]: Add generic built instructions for making a dynamic library on all platforms

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#84]
Hi,
With the understanding that I have no idea about cmake processes, so really have no business suggesting new build commands, I have found that on all platforms, `cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DSYNTHIZER_LIB_TYPE=SHARED` builds a dynamic library that can be used with bindings.

I know there's already the build command for windows, but the above works just as well, and has the advantage of working on at least Linux (and I assume Mac OS) as well.

With your permission, I'll modify the readme, to take out the bit about building a multithreaded library, and including the above command, with an explanation that it'll work on all platforms to build a dynamic library suitable for calling from other languages' FFI implementations.

What do you think?

**Comment by ahicks92** [comment]
I mean sure, there you go.

**Comment by chrisnorman7** [comment]
I was more than happy to do it myself, but thank you very much!

Take care,

Chris Norman
