### ISSUE TITLE
Synthizer does not terminate if the program exits prematurely

### ISSUE THREAD

**Issue by thgcode** [synthizer/synthizer#89]
When the program exits prematurely, for example if it gives an error and calls exit(), Synthizer causes the program not to exit, or in some cases opens a debug dialog.
Example code that causes the problem:
```
#include "synthizer.h"

#include <stdio.h>

int main() {
  syz_initialize();

  exit(1);
}
```

This exit call could be caused by other circunstances, for example an exception on the program. While I think the behavior of the program is not correct to not try to shutdown Synthizer, Synthizer could quit the program normally.

**Comment by ahicks92** [comment]
Like many other C libraries, Synthizer requires to be properly uninitialized.  If you don't then yes, things go wrong.  I can't stop background threads on your behalf, that's just not something which can reliably be done.
