### ISSUE TITLE
Python Type Hints

### ISSUE THREAD

**Issue by chrisnorman7** [synthizer/synthizer#9]
Hi,
Now I'm using Synthizer in my own projects, it would be extremely useful to have Python type hinting.

Is this something you're interested in?

I'm more than happy to port the existing code myself, or even be responsible for type hints in the code base, if that would be helpful.

I'm going to have a poke around in the build/python directory to see what's going on there. If you're interested in this feature and / or help with it, could you let me know if there's anywhere else I should be looking?

Not really sure what other questions to ask at this stage.

**Comment by camlorn** [comment]
I'm not adverse to this, but it changes frequently enough that I'd probably need to be responsible for maintaining them, I've not done it before, and I don't know how well it works with Cython (though I think they have annotation support now).  If you or someone else gets it working and wants to send a PR I'll merge and keep it up to date, but building Synthizer from source is required to build the bindings.

It's a good idea, but we have bigger fish to fry like not being able to loop streams, so unless someone else does the work it won't happen for a while.

**Comment by chrisnorman7** [comment]
OK,
As I said, I'm happy to be responsible for it, if you just let me know when
it's stable enough that it won't change on an hourly basis.

I've only just started using type hints in Python myself, and it's easier
than I gave it credit for. Especially with Synthizer, where many of the
functions are primitive types anyways (int, float, bool).

Basic idea is:

def f(a: int, b: int) -> int:
    """Add two numbers together."""
    return a + b

Take care,

Chris Norman

**Comment by camlorn** [comment]
It's stable enough that if you give me an initial version I can keep it updated, which is what I was trying and failing to say.

I'm familiar with the Python-side annotations but I don't know how this interacts with Cython and I'm not set up to easily find out if they're working, either.

**Comment by chrisnorman7** [comment]
OK, do I just put changes in the bindings/python/synthizer/synthizer.pyx
file? or are there other places?

Also, are there build instructions, so I can test the version I build?

Take care,

Chris Norman

**Comment by camlorn** [comment]
Yeah. The annotations would go in synthizer.pyx.  Build instructions are on the to-do list but it's the standard cmake out-of-tree process.  Get VS 2019 with all the C++ tools, get Clang from releases.llvm.org, then:

```
mkdir build
cd build
cmake -G Ninja -DCMAKE_C_COMPILER="c:\program files\llvm\bin\clang-cl.exe" -DCMAKE_CXX_COMPILER="c:\program files\llvm\bin\clang-cl.exe" ..
ninja
```

Only need `ninja` after the first time, but since you're doing Python you'll be good and don't need to rebuild this. Then, for Python, using powershell:

```
cd bindings\python
$Env:BUILDING_SYNTHIZER=1
python setup.py develop
```

That's all typed from memory, so there might be errors or omissions.  Also if you don't have the tools already it'll take quite a while to set up unless you've got good internet.

**Comment by camlorn** [comment]
@chrisnorman7 
I'm going to look at this as part of 1.0. Is there a convenient way to test to make sure they're working?  Which VSCode extensions do you use?  Any help is appreciated.

**Comment by chrisnorman7** [comment]
@camlorn I'm using [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance), which pretty well does it all. Just make sure you've got [Mypy](https://mypy.readthedocs.io/en/stable/) installed.

When you start typing member names, autocomplete should come up and show you what the type of a value should be.

Let me know if there's anything else you need to know, and sorry I never got around to looking at the type hinting myself. I did look into cython briefly, but when I failed to build Synthizer I sort of forgot about it.

**Comment by camlorn** [comment]
Unfortunately, I just don't have the bandwidth and there's too many other fish to fry.  I need someone to start by creating typing information for the current bindings, whether that be through figuring out if/how Cython can annotate or if we can maintain a separate index, and to get them relatively in sync with what exists. If someone gets it that far I'll revisit and put this in a milestone, though possibly not 1.0.

**Comment by chrisnorman7** [comment]
That's fine. I'll look into making stubs at some point.

Cheers,

Take care,

Chris Norman

**Comment by chrisnorman7** [comment]
I'm currently experimenting with [Automatic stub generation (stubgen)](https://mypy.readthedocs.io/en/stable/stubgen.html# "Automatic stub generation (stubgen)"), to generate type stubs for Synthizer, for use in Earwax.

If I'm successful, do you want a PR with the stubs I've made?

The original stub file was created with `stubgen -m synthizer`, and I'm just modifying the types by hand.

**Comment by camlorn** [comment]
I would want a PR if you can get it actually working with Synthizer itself on install.  Otherwise, I don't much see the value.

**Comment by chrisnorman7** [comment]
OK, so I've made a stub file, and it works fine. I'm not sure where to place it in the Synthizer source tree though.

It works from the route directory of the Earwax source tree, so MyPy is recognising it, and it giving me the expected things.

I was going to put it into site-packages inside the synthizer folder, but there isn't one.

Where would I put it for a PR to ensure it's shipped with the Synthizer module?

**Comment by camlorn** [comment]
I don't know.  I think maybe you modify Manifest.in.  You'll have to build the package, install it, and check if files go where they're supposed to.

Advanced Python packaging is where good devs go to die of frustration. It's not even fully documented in one place.

**Comment by chrisnorman7** [comment]
OK, I can do that. Are there build instructions somewhere? I've managed to
build with cmake. Do I then just read the ps1 files in the binding/python
directory to see what happens next?

Take care,

Chris Norman

**Comment by camlorn** [comment]
The readme tells you how to build Python too if you read the section on Python.  Do you need more clarification than than what I've got there?

Also left you a review on your PR.
